# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, unique=True)),
                ('author', models.CharField(default='Simon', max_length=100)),
                ('tags', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(blank=True, max_length=15000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
