# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogEntry',
            new_name='BlogPost',
        ),
    ]
