# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151227_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
    ]
